spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      username: lionel
      password: lionel
      database: reservehubClient
      authentication-database: admin

server:
  port: 8901

eureka:
  client:
    serviceUrl:
      defaultZone: http://reserve-hub-discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show:
        details: always
