server:
  port: 10140
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reserve-hub-utilisateur-server
          uri: lb:http://RESERVE-HUB-UTILISATEUR-SERVER
          predicates:
            - Path=/api/v1/utilisateur/**

eureka:
  client:
    serviceUrl:
      defaultZone:  http://reserve-hub-discovery-server-peer1:10120/eureka/, http://reserve-hub-discovery-server-peer2:10140/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show:
        details: always
