server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: reserve-hub-utilisateur-server
          uri: lb:http://RESERVE-HUB-UTILISATEUR-SERVER
          predicates:
            - Path=/api/v1/utilisateur/**
