spring:
  data:
    mongodb:
      host: mongodb
      port: 10410
      username: lionel
      password: lionel
      database: reservehubClient
      authentication-database: admin

server:
  port: 10210

eureka:
  client:
    serviceUrl:
      defaultZone: http://reserve-hub-discovery-server-peer1:10120/eureka/, http://reserve-hub-discovery-server-peer2:10130/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show:
        details: always

logging:
  level:
    root: INFO
    org.springframework: INFO
  file:
    name: logs/${spring.application.name}.log
